# -*- coding: utf-8 -*-
"""ML Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HzRwssTZkDbCmJ44vZmbY0jiJa4uRCI

# 1)Вспомнить всё: if
"""

T = float(input())
if T < 15.5:
  print('Холодно')
else:
  if T > 28:
    print('Жарко')
  else:
    print('Нормально')

"""# 2)Найди кота"""

print(["МЯУ", "НЕТ"][0**len([x for x in [input() for i in range(int(input()))] if "кот" in x.lower()])])

"""# 3)Слова и буквы"""

slova = input()
minx = slova
maxx = slova
y = 'ДА'
n = 'НЕТ'
while True:
    slova = input()
    if slova == 'стоп':
        if len(set(minx) - set(maxx)) == 0:
            print(y)
            break
        else :
            print(n)
            break

    if len(slova) > len(maxx):
        maxx = slova
    if len(slova) < len(minx):
        minx = slova

"""# 4)Список покупок"""

n = int(input())
spisok = list()
for i in range(0,n,1):
  spisok.append(str(input()))
for i in range(0,n,1):
  print(spisok[i])

"""# 5)Ххооллоод"""

STR = str(input())
doubleSTR = list()
for i in STR:
  doubleSTR.extend([i,i])
print(''.join(doubleSTR))

"""# 6)Формальное приветствие"""

def greet():
  print('Ваше имя?')
  name = str(input())
  print('Ваша фамилия?')
  surname = str(input())
  print('Здравствуйте,'+' '+name+" " + surname + '.')
greet()

"""# 7*)Маленький колокольчик
Я не делал отдельный файл
"""

class LittleBell():
  def __init__(self):
    self.ding = 'ding'
  def sound(self):
    print(self.ding)

bell= LittleBell()
bell.sound()
bell.sound()
bell.sound()

"""# 8)Остаточные знания

Доброго времени суток, читатель! Я являюсь студентом 4 курса ФФ.
На первом курсе прошли базовый курс на языке C.
На втором курсе в 3 семестре наш преподаватель скопировал курс от Яндекса по C++, который мы успешно завершили. Тогда я познакомился с платформой GitHub.
В 4 семестре началось изучения MATLAB, там мы занимались моделированием различных физических процессов. Самостоятельно писать код на MATLAB было тяжело, но разобраться в написанном другими проблем не составляло.
На третьем курсе проблемно освоена дисциплина ТСАНИ.
На четвертом курсе закрыл предмет ОВФ. Писал и списывал) коды на питоне, поскольку необходимо было графически представлять результаты.
"""